default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails
  password: password
  host: mysql

development:
  <<: *default
  database: bulk_registration_form_example_development

test:
  <<: *default
  database: bulk_registration_form_example_test

production:
  <<: *default
  database: bulk_registration_form_example_production
  username: rails
  password: <%= ENV['BACKEND_DATABASE_PASSWORD'] %>
